{
  parserClass="com.github.syuchan1005.gitprefix.psi.PrefixResourceParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="PrefixResource"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.syuchan1005.gitprefix.psi"
  psiImplPackage="com.github.syuchan1005.gitprefix.psi.impl"

  elementTypeHolderClass="com.github.syuchan1005.gitprefix.psi.PrefixResourceTypes"
  elementTypeClass="com.github.syuchan1005.gitprefix.psi.PrefixResourceElementType"
  tokenTypeClass="com.github.syuchan1005.gitprefix.psi.PrefixResourceTokenType"
}

prefixResourceFile ::= item_*


private item_ ::= (property|LINE_COMMENT|BLOCK_COMMENT|WHITE_SPACE)

property ::= (EMOJI_KEY|TEXT_KEY) (TEXT_VALUE|EMOJI_VALUE)?

