name: Verify Plugin

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: git submodule
        run: git submodule update --init --recursive
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew buildPlugin
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
      - uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.2.1
        with:
          plugin-location: "./build/libs/GitPrefix.jar"
          ide-versions: |
            ideaIU:2017.3.6
            ideaIU:2018.3.6
            ideaIU:2019.1.4
            ideaIU:2019.3.5
            ideaIU:2020.1.3
            ideaIU:LATEST-EAP-SNAPSHOT
